/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ummisco_gama_chemmisol_ChemicalSystem */

#ifndef _Included_ummisco_gama_chemmisol_ChemicalSystem
#define _Included_ummisco_gama_chemmisol_ChemicalSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_allocate__
  (JNIEnv *, jclass);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    allocate
 * Signature: (DDD)J
 */
JNIEXPORT jlong JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_allocate__DDD
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_dispose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    addReaction
 * Signature: (JLummisco/gama/chemmisol/Reaction;)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_addReaction
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    addComponent
 * Signature: (JLummisco/gama/chemmisol/ChemicalComponent;)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_addComponent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    fixPH
 * Signature: (JDLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_fixPH
  (JNIEnv *, jclass, jlong, jdouble, jstring);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    setTotalConcentration
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_setTotalConcentration
  (JNIEnv *, jclass, jlong, jstring, jdouble);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    setUp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_setUp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    solve
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_solve
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    concentration
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_concentration
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    reactionQuotient
 * Signature: (JLjava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_reactionQuotient
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    sitesQuantity
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_sitesQuantity
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
