/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ummisco_gama_chemmisol_ChemicalSystem */

#ifndef _Included_ummisco_gama_chemmisol_ChemicalSystem
#define _Included_ummisco_gama_chemmisol_ChemicalSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_allocate
  (JNIEnv *, jobject);

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
