/* DO NOT EDIT THIS FILE - it is machine generated */
#include <chemmisol/ummisco_gama_chemmisol_ChemicalSystem.h>

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_allocate
(JNIEnv *, jobject) {
	return 0;
}

/*
 * Class:     ummisco_gama_chemmisol_ChemicalSystem
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ummisco_gama_chemmisol_ChemicalSystem_dispose
(JNIEnv *, jobject, jlong) {
}
